name: nhai_auth
description: NHAI Offline Edge-AI Authentication Infrastructure — Phase 1 MVP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  tflite_flutter: ^0.10.4
  camera: ^0.10.5+9
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
